export const DEMO_SCENARIO = {
  disaster_type: "Flood",
  location: "Hubballi - Varur Region",
  latitude: 15.3647,
  longitude: 75.124,
  severity_level: 80,
  affected_population: 20000,
  vulnerable_population: 5000,
  available_rescue_teams: 12,
  required_rescue_teams: 15,
  hospital_capacity: 500,
  estimated_injured: 700,
  blocked_roads: 4,
  weather_condition: "Heavy rainfall expected for 6 hours",
  response_time_limit: 6,
  budget_level: "Medium",
};

export const DEMO_RESOURCES = {
  "Medical Resource Officer": {
    role: "Medical Resource Officer",
    location: "Hubballi",
    doctors: 45,
    ambulances: 12,
    hospital_beds: 480,
    medical_camps: 3,
    first_aid_kits: 200,
    blood_units: 150,
  },
  "Rescue Resource Officer": {
    role: "Rescue Resource Officer",
    location: "Hubballi",
    rescue_teams: 30,
    boats: 6,
    life_jackets: 250,
    ropes: 40,
    divers: 8,
    emergency_vehicles: 5,
  },
  "Fire and Safety Officer": {
    role: "Fire and Safety Officer",
    location: "Hubballi",
    firefighters: 20,
    fire_trucks: 4,
    safety_teams: 6,
    danger_zones: 3,
  },
  "NGO / Volunteer Coordinator": {
    role: "NGO / Volunteer Coordinator",
    location: "Hubballi",
    volunteers: 120,
    food_packets: 2000,
    water_bottles: 5000,
    clothes: 800,
    blankets: 600,
  },
  "Transport Officer": {
    role: "Transport Officer",
    location: "Hubballi",
    blocked_roads_count: 4,
    safe_roads: 6,
    damaged_bridges: 2,
    available_buses: 18,
    route_status: "Partially operational",
  },
};
